# Generated by Django 5.2.10 on 2026-01-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach_subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersubjects',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teachersubjects',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
