# Generated by Django 5.2.10 on 2026-01-27 02:51

import django.contrib.postgres.fields
import django.db.models.deletion
import group.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_id_students_user_account_and_more'),
        ('group', '0001_initial'),
        ('teach_subject', '0002_rename_subject_id_teachersubjects_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroups',
            old_name='descrition',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='studentgroups',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='studentgroups',
            name='lead_teacher',
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='status',
            field=models.CharField(choices=[('AT', 'Active'), ('FG', 'Finished'), ('DF', 'Disqualified')], default='AT', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=group.models.get_default_tags, help_text='Tags of group projects type', size=None),
        ),
        migrations.AddField(
            model_name='studentgroups',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teach_subject.teachersubjects'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.studentgroups'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.students'),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='project_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentgroups',
            name='term',
            field=models.PositiveIntegerField(help_text='The term in which the project started'),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_url', models.URLField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.students')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='group.projecttask')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.studentgroups')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
