# Generated by Django 4.2.1 on 2025-07-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuochop',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('meettime', models.DateTimeField(blank=True, null=True)),
                ('isreported', models.BooleanField(blank=True, null=True)),
                ('isscheduled', models.BooleanField(blank=True, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=254, null=True)),
                ('idnhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.nhom')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_url', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.CharField(blank=True, max_length=100, null=True)),
                ('cuochop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='meetings.cuochop')),
            ],
        ),
    ]
