# Generated by Django 5.2.10 on 2026-01-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='group_id',
            new_name='student_group',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='meeting_id',
            new_name='meeting',
        ),
    ]
