# Generated by Django 5.2.10 on 2026-01-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_user_id_students_user_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='fullName',
            new_name='full_name',
        ),
    ]
