# Generated by Django 4.2.1 on 2023-07-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_authgroup1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="id",
            new_name="user_id",
        ),
    ]
