# Generated by Django 4.2.1 on 2023-07-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_id_useraccount_user_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cuochop",
        ),
        migrations.RemoveField(
            model_name="mon",
            name="mamon",
        ),
        migrations.DeleteModel(
            name="Nhom",
        ),
        migrations.DeleteModel(
            name="Note",
        ),
        migrations.DeleteModel(
            name="Sinhvien",
        ),
        migrations.DeleteModel(
            name="Giangvien",
        ),
        migrations.DeleteModel(
            name="Mon",
        ),
    ]
