# Generated by Django 4.2.1 on 2023-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_delete_cuochop_remove_mon_mamon_delete_nhom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuochop",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "meettime",
                    models.DateTimeField(blank=True, db_column="MeetTime", null=True),
                ),
                (
                    "isnoted",
                    models.IntegerField(blank=True, db_column="isNoted", null=True),
                ),
            ],
            options={
                "db_table": "cuochop",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Giangvien",
            fields=[
                (
                    "magv",
                    models.CharField(
                        db_column="MaGV",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hotengb",
                    models.CharField(
                        blank=True, db_column="HoTenGB", max_length=40, null=True
                    ),
                ),
                (
                    "vien",
                    models.CharField(
                        blank=True, db_column="Vien", max_length=100, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "giangvien",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mon",
            fields=[
                (
                    "mamon",
                    models.CharField(
                        db_column="MaMon",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tenmon",
                    models.CharField(
                        blank=True, db_column="TenMon", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "mon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nhom",
            fields=[
                (
                    "idnhom",
                    models.CharField(
                        db_column="IdNhom",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term",
                    models.PositiveIntegerField(
                        blank=True, db_column="Term", null=True
                    ),
                ),
                (
                    "tennhom",
                    models.CharField(
                        blank=True, db_column="TenNhom", max_length=10, null=True
                    ),
                ),
                (
                    "tendetai",
                    models.CharField(
                        blank=True, db_column="TenDetai", max_length=100, null=True
                    ),
                ),
                (
                    "projectstatus",
                    models.IntegerField(
                        blank=True, db_column="ProjectStatus", null=True
                    ),
                ),
            ],
            options={
                "db_table": "nhom",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "noteid",
                    models.CharField(
                        db_column="NoteId",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, db_column="Note", max_length=100, null=True
                    ),
                ),
                (
                    "report",
                    models.CharField(
                        blank=True, db_column="Report", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "note",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sinhvien",
            fields=[
                (
                    "masv",
                    models.CharField(
                        db_column="MaSV",
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hoten",
                    models.CharField(
                        blank=True, db_column="HoTen", max_length=40, null=True
                    ),
                ),
                (
                    "malop",
                    models.CharField(
                        blank=True, db_column="MaLop", max_length=10, null=True
                    ),
                ),
                (
                    "sdt",
                    models.CharField(
                        blank=True, db_column="SDT", max_length=10, null=True
                    ),
                ),
                (
                    "nganh",
                    models.CharField(
                        blank=True, db_column="Nganh", max_length=30, null=True
                    ),
                ),
                (
                    "emailsv",
                    models.CharField(
                        blank=True, db_column="EmailSV", max_length=20, null=True
                    ),
                ),
            ],
            options={
                "db_table": "sinhvien",
                "managed": False,
            },
        ),
    ]
